<img src="https://upload.wikimedia.org/wikipedia/commons/4/47/Logo_UTFSM.png" width="200" alt="utfsm-logo" align="left"/>

# MAT281
### Aplicaciones de la Matemática en la Ingeniería

## Módulo 02
## Clase 01: Computación Científica

## Objetivos

* Conocer las librerías de computación científica
* Trabajar con arreglos *matriciales*
* Álgebra lineal con numpy

## Contenidos
* [Scipy.org](#scipy.org)
* [Numpy Arrays](#arrays)
* [Operaciones Básicas](#operations)
* [Broadcasting](#roadcasting)
* [Álgebra Lineal](#linear_algebra)

<a id='scipy.org'></a>
## SciPy.org

**SciPy** es un ecosistema de software _open-source_ para matemática, ciencia y engeniería. Los principales son:

* Numpy: Arrays N-dimensionales. Librería base, integración con C/C++ y Fortran.
* Scipy library: Computación científica (integración, optimización, estadística, etc.)
* Matplotlib: Visualización 2D:
* IPython: Interactividad (Project Jupyter).
* Simpy: Matemática Simbólica.
* Pandas: Estructura y análisis de datos.

<a id='arrays'></a>
## Numpy Arrays

Los objetos principales de Numpy son los comúnmente conocidos como Numpy Arrays (la clase se llama `ndarray`), corresponden a una tabla de elementos, todos del mismo tipo, indexados por una tupla de enternos no-negativos. En Numpy, las dimensiones son llamadas _axes_. 

In [1]:
import numpy as np

In [2]:
a = np.array(
    [
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]
    ]
)

type(a)

numpy.ndarray

Los atributos más importantes de un `ndarray` son:

In [3]:
a.shape  # the dimensions of the array.

(3, 5)

In [4]:
a.ndim  # the number of axes (dimensions) of the array.

2

In [5]:
a.size  # the total number of elements of the array.

15

In [6]:
a.dtype  # an object describing the type of the elements in the array. 

dtype('int64')

In [7]:
a.itemsize  # the size in bytes of each element of the array.

8

### Crear Numpy Arrays

Hay varias formas de crear arrays, el constructor básico es el que se utilizó hace unos momentos, `np.array`. El _type_ del array resultante es inferido de los datos proporcionados. 

In [8]:
a_int = np.array([2, 6, 10])
a_float = np.array([2.1, 6.1, 10.1])

print(f"a_int: {a_int.dtype.name}")
print(f"a_float: {a_float.dtype.name}")

a_int: int64
a_float: float64


### Constantes

In [9]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2, 3, 4), dtype=np.int)  # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [11]:
np.identity(4)  # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Range

Numpy proporciona una función análoga a `range`.

In [12]:
range(10)

range(0, 10)

In [13]:
type(range(10))

range

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
type(np.arange(10))

numpy.ndarray

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(2, 20, 3, dtype=np.float)

array([ 2.,  5.,  8., 11., 14., 17.])

In [18]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# Bonus
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

### Random

In [20]:
np.random.uniform(size=5)

array([0.30388068, 0.5396812 , 0.85970245, 0.02295638, 0.2942638 ])

In [21]:
np.random.normal(size=(2, 3))

array([[-0.92011337, -0.72546984, -0.83882933],
       [-0.01366339, -0.22968873,  0.06936561]])

### Acceder a los elementos de un array

In [22]:
x1 = np.arange(0, 30, 4)
x2 = np.arange(0, 60, 3).reshape(4, 5)
print("x1:")
print(x1)
print("\nx2:")
print(x2)

x1:
[ 0  4  8 12 16 20 24 28]

x2:
[[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 33 36 39 42]
 [45 48 51 54 57]]


In [23]:
x1[1]  # Un elemento de un array 1D

4

In [24]:
x1[:3]  # Los tres primeros elementos

array([0, 4, 8])

In [25]:
x2[0, 2]  # Un elemento de un array 2D

6

In [26]:
x2[0]  # La primera fila

array([ 0,  3,  6,  9, 12])

In [27]:
x2[:, 1]  # Todas las filas y la segunda columna

array([ 3, 18, 33, 48])

In [28]:
x2[:, 1:3]  # Todas las filas y de la segunda a la tercera columna

array([[ 3,  6],
       [18, 21],
       [33, 36],
       [48, 51]])

In [29]:
x2[:, 1:2]  # What?!

array([[ 3],
       [18],
       [33],
       [48]])

<a id='operations'></a>
## Operaciones Básias

Numpy provee operaciones vectorizadas, con tal de mejorar el rendimiento de la ejecución.

Por ejemplo, pensemos en la suma de dos arreglos 2D.

In [30]:
A = np.random.random((5,5))
B = np.random.random((5,5))

Con los conocimientos de la clase pasada, podríamos pensar en iterar a través de dos `for`, con tal de llenar el arreglo resultando. algo así:

In [31]:
def my_sum(A, B):
    n, m = A.shape
    C = np.empty(shape=(n, m))
    for i in range(n):
        for j in range(m):
            C[i, j] = A[i, j] + B[i, j]
    return C

In [32]:
%timeit my_sum(A, B)

25.6 µs ± 1.73 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Pero la suma de `ndarray`s es simplemente con el signo de suma (`+`):

In [33]:
%timeit A + B 

760 ns ± 44.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Para dos arrays tan pequeños la diferencia de tiempo es considerable, ¡Imagina con millones de datos!

Los clásicos de clásicos:

In [34]:
x = np.arange(5)
print(f"x      = {x}")
print(f"x + 5  = {x + 5}")
print(f"x - 5  = {x - 5}")
print(f"x * 2  = {x * 2}")
print(f"x / 2  = {x / 2}")
print(f"x // 2 = {x // 2}")
print(f"x ** 2 = {x ** 2}")
print(f"x % 2  = {x % 2}")

x      = [0 1 2 3 4]
x + 5  = [5 6 7 8 9]
x - 5  = [-5 -4 -3 -2 -1]
x * 2  = [0 2 4 6 8]
x / 2  = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]
x ** 2 = [ 0  1  4  9 16]
x % 2  = [0 1 0 1 0]


¡Júntalos como quieras!

In [35]:
-(0.5 + x + 3) ** 2

array([-12.25, -20.25, -30.25, -42.25, -56.25])

Al final del día, estos son alias para funciones de Numpy, por ejemplo, la operación suma (`+`) es un _wrapper_ de la función `np.add`

In [36]:
np.add(x, 5)

array([5, 6, 7, 8, 9])

Podríamos estar todo el día hablando de operaciones, pero básicamente, si piensas en alguna operación lo suficientemente común, es que la puedes encontrar implementada en Numpy. Por ejemplo:

In [37]:
np.abs(-(0.5 + x + 3) ** 2)

array([12.25, 20.25, 30.25, 42.25, 56.25])

In [38]:
np.log(x + 5)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [39]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [40]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### ¿Y para dimensiones mayores?

La idea es la misma, pero siempre hay que tener cuidado con las dimensiones y `shape` de los arrays.

In [41]:
print("A + B: \n")
print(A + B)
print("\n" + "-" * 80 + "\n")
print("A - B: \n")
print(A - B)
print("\n" + "-" * 80 + "\n")
print("A * B: \n")
print(A * B)  # Producto elemento a elemento
print("\n" + "-" * 80 + "\n")
print("A / B: \n")
print(A / B)  # División elemento a elemento
print("\n" + "-" * 80 + "\n")
print("A @ B: \n")
print(A @ B)  # Producto matricial

A + B: 

[[1.44375336 0.71089839 1.55517344 1.07142834 0.19377612]
 [1.10159517 0.73722265 0.22819925 0.87266868 1.20170862]
 [1.4082673  0.94901585 0.37486928 1.38757357 1.11262864]
 [0.44423052 0.57013697 1.08392427 1.17498388 0.7877744 ]
 [0.21582357 0.64130869 0.97313579 1.13187875 1.42643214]]

--------------------------------------------------------------------------------

A - B: 

[[ 0.28689194 -0.47859742  0.37789763 -0.5219611   0.09782708]
 [ 0.57742103  0.09577488  0.10352215  0.16516056 -0.18663976]
 [-0.02119136  0.48983    -0.19130114 -0.53112721 -0.10077731]
 [-0.05418863 -0.34275016  0.4858589  -0.02888329 -0.4296817 ]
 [ 0.05373797  0.05354702  0.30201878 -0.44963618 -0.01006373]]

--------------------------------------------------------------------------------

A * B: 

[[0.5005292  0.06908026 0.56893946 0.21887882 0.00699476]
 [0.22002422 0.1335811  0.01033952 0.18356815 0.3523173 ]
 [0.49569193 0.16517441 0.02598271 0.41081608 0.30694661]
 [0.04860109 0.05189462 0.

### Operaciones Booleanas

In [42]:
print(f"x      = {x}")
print(f"x > 2  = {x > 2}")
print(f"x == 2 = {x == 2}")
print(f"x == 2 = {x == 2}")

x      = [0 1 2 3 4]
x > 2  = [False False False  True  True]
x == 2 = [False False  True False False]
x == 2 = [False False  True False False]


In [43]:
aux1 = np.array([[1, 2, 3], [2, 3, 5], [1, 9, 6]])
aux2 = np.array([[1, 2, 3], [3, 5, 5], [0, 8, 5]])

B1 = aux1 == aux2
B2 = aux1 > aux2

print("B1: \n")
print(B1)
print("\n" + "-" * 80 + "\n")
print("B2: \n")
print(B2)
print("\n" + "-" * 80 + "\n")
print("~B1: \n")
print(~B1)  # También puede ser np.logical_not(B1)
print("\n" + "-" * 80 + "\n")
print("B1 | B2 : \n")
print(B1 | B2)
print("\n" + "-" * 80 + "\n")
print("B1 & B2 : \n")
print(B1 & B2)

B1: 

[[ True  True  True]
 [False False  True]
 [False False False]]

--------------------------------------------------------------------------------

B2: 

[[False False False]
 [False False False]
 [ True  True  True]]

--------------------------------------------------------------------------------

~B1: 

[[False False False]
 [ True  True False]
 [ True  True  True]]

--------------------------------------------------------------------------------

B1 | B2 : 

[[ True  True  True]
 [False False  True]
 [ True  True  True]]

--------------------------------------------------------------------------------

B1 & B2 : 

[[False False False]
 [False False False]
 [False False False]]


<a id='broadcasting'></a>
## Broadcasting

¿Qué pasa si las dimensiones no coinciden? Observemos lo siguiente:

In [44]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

Todo bien, dos arrays 1D de 3 elementos, la suma retorna un array de 3 elementos. 

In [45]:
a + 3

array([3, 4, 5])

Sigue pareciendo normal, un array 1D de 3 elementos, se suma con un `int`, lo que retorna un array 1D de tres elementos.

In [46]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Magia! Esto es _broadcasting_. Una pequeña infografía es la siguiente:

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

Resumen: A lo menos los dos arrays deben coincidir en una dimensión. Luego, el array de dimensión menor se extiende con tal de ajustarse a las dimensiones del otro.

La documentación oficial de estas reglas la puedes encontrar [aquí](https://numpy.org/devdocs/user/basics.broadcasting.html).

<a id='lineal_algebra'></a>
## Álgebra Lineal

Veamos algunas operaciones básicas de álgebra lineal, las que te servirán para el día a día.

In [48]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


Transpuesta

In [49]:
a.T  # a.transpose() 

array([[1., 3.],
       [2., 4.]])

Determinante

In [50]:
np.linalg.det(a)

-2.0000000000000004

Inversa

In [51]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Traza

In [52]:
np.trace(a)

5.0

Número de condición

In [53]:
np.linalg.cond(a)

14.933034373659268

Sistemas lineales

In [54]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

Valores y vectores propios 

In [55]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Descomposición QR

In [56]:
np.linalg.qr(a)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))